# conda env create|update -f conda_env.yml
# source activate hands-on-machine-learning
# ...
# source deactivate
# conda env remove hands-on-machine-learning
name: deep-learning-with-keras
dependencies:
  - python=3.6

  - keras-gpu
  - matplotlib
  - numpy
  - opencv
  - pandas
  - tensorflow-gpu

  - pip
    - keras-adversarial

