# conda env create|update -f conda_env.yml
# source activate hands-on-machine-learning
# ...
# source deactivate
# conda env remove hands-on-machine-learning
name: hands-on-machine-learning
dependencies:
  - python=3.6

  - matplotlib
  - numpy
  - pandas
  # sklearn 0.19 has a change which causes problem:
  # https://stackoverflow.com/questions/46162855/fit-transform-takes-2-positional-arguments-but-3-were-given-with-labelbinarize
  - scikit-learn=0.18
  - tensorflow-gpu

  - pip:
    - bpython
